In [92]:
import numpy as np

In [93]:
np

<module 'numpy' from 'C:\\Users\\GODIAN\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\__init__.py'>

In [94]:
np.__version__

'1.23.1'

### Creating arrays

In [95]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [96]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [97]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [98]:
a = np.array([2,4,6,8,10,12,14,16,18,20])
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [99]:
a[3]= 18
a

array([ 2,  4,  6, 18, 10, 12, 14, 16, 18, 20])

In [100]:
np.arange(5, 100, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [101]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Multi-Dimensional Arrays

In [102]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [103]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
a[1,1]

5

In [105]:
a[2,0] = 14

In [106]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [14,  8,  9]])

In [107]:
a[1] = [10, 20, 30]
a

array([[ 1,  2,  3],
       [10, 20, 30],
       [14,  8,  9]])

In [108]:
a[:,2]

array([ 3, 30,  9])

### Randomly Generated Arrays

In [109]:
np.random.seed(2)  # To fix the random seed
100*np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [110]:
np.random.seed(2)  
np.random.randn(5,2) # Normal

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [111]:
np.random.seed(2)  
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### Element-wise Operations

In [112]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
a + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [114]:
a * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [115]:
b = ((a * 2)*(a + 2))**2
b

array([    0,    36,   256,   900,  2304,  4900,  9216, 15876, 25600,
       39204])

In [116]:
a + b

array([    0,    37,   258,   903,  2308,  4905,  9222, 15883, 25608,
       39213])

### Comparison Operations

In [117]:
a >= 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [118]:
b <= a

array([ True, False, False, False, False, False, False, False, False,
       False])

In [119]:
a[a < b]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Summarizing Operations

In [120]:
a.min()

0

In [121]:
b.max()

39204

In [122]:
a.sum()

45

In [123]:
b.mean()

9829.2

In [124]:
b.std()

12622.833159001982

In [125]:
a.max()

9

### Linear Algebra

In [126]:
x = np.array((1,4,3,6))
x

array([1, 4, 3, 6])

In [127]:
x * 2

array([ 2,  8,  6, 12])

In [128]:
y = np.array((7,3,8,5))
y

array([7, 3, 8, 5])

In [129]:
x + y

array([ 8,  7, 11, 11])

In [130]:
y + x

array([ 8,  7, 11, 11])

In [131]:
x * y

array([ 7, 12, 24, 30])

### Mutiplication

In [132]:
def vector_vector_multiplication(x,y):
    assert x.shape[0] == y.shape[0]
    
    n = x.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result = result + x[i] * y[i]
        
    return result
    

In [133]:
vector_vector_multiplication(x,y)

73.0

In [134]:
x.dot(y)

73

#### Matrix-Vector Multiplication

In [135]:
Z = np.array([[1,3,6,8],
              [2,5,9,6],
              [7,9,4,5]])

In [136]:
Z

array([[1, 3, 6, 8],
       [2, 5, 9, 6],
       [7, 9, 4, 5]])

In [137]:
def matrix_vector_multiplication(Z, y):
    assert Z.shape[1] == y.shape[0]
    
    num_rows = Z.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(Z[i], y)
        
    return result 

In [138]:
matrix_vector_multiplication(Z, y)

array([104., 131., 133.])

In [139]:
Z.dot(y)

array([104, 131, 133])

#### Matrix-Matrix Multiplication

In [140]:
A = np.array([[3,5,6],[3,5,7],[7,9,9],[1,0,8]])
A

array([[3, 5, 6],
       [3, 5, 7],
       [7, 9, 9],
       [1, 0, 8]])

In [141]:
Z

array([[1, 3, 6, 8],
       [2, 5, 9, 6],
       [7, 9, 4, 5]])

In [142]:
def matrix_matrix_multiplication(Z, A):
    assert Z.shape[1] == A.shape[0]
    
    num_rows = Z.shape[0]
    num_cols = A.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        ai = A[:, i]
        Zai = matrix_vector_multiplication(Z, ai)
        result[:, i] = Zai
        
    return result

In [143]:
matrix_matrix_multiplication(Z, A)

array([[ 62.,  74., 145.],
       [ 90., 116., 176.],
       [ 81., 116., 181.]])

In [144]:
Z.dot(A)

array([[ 62,  74, 145],
       [ 90, 116, 176],
       [ 81, 116, 181]])

In [145]:
Z.shape

(3, 4)

In [146]:
A.shape

(4, 3)

In [147]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [148]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [149]:
I.dot(Z)

array([[1., 3., 6., 8.],
       [2., 5., 9., 6.],
       [7., 9., 4., 5.]])

In [150]:
Z

array([[1, 3, 6, 8],
       [2, 5, 9, 6],
       [7, 9, 4, 5]])

In [151]:
A

array([[3, 5, 6],
       [3, 5, 7],
       [7, 9, 9],
       [1, 0, 8]])

### Inverse

In [152]:
As = A[[0,1,2]]
As

array([[3, 5, 6],
       [3, 5, 7],
       [7, 9, 9]])

In [153]:
As_inv = np.linalg.inv(As)
As_inv

array([[-2.25 ,  1.125,  0.625],
       [ 2.75 , -1.875, -0.375],
       [-1.   ,  1.   , -0.   ]])

In [154]:
As_inv.dot(As)

array([[ 1.00000000e+00,  8.88178420e-16,  0.00000000e+00],
       [-4.44089210e-16,  1.00000000e+00, -2.22044605e-15],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [155]:
import pandas as pd

In [156]:
df = pd.read_csv('data.csv')

In [157]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [158]:
data = {'Make': ['Nissan','Hyundai','Lotus','GMC','Nissan'],
       'Model': ['Stanza','Sonata','Elise','Acadia','Frontia'],
       'Year': [1991, 2017, 2010, 2017,2017],
       'Engine HP': [138, None, 218, 194, 261],
       'Engine Cylinders': [4, 4, 4, 4, 6],
       'Transmission Type': ['MANUAL', 'AUTOMATIC', 'MANUAL', 'AUTOMATIC', 'MANUAL'],
       'Vehicle Style': ['sedan', 'Sedan', 'convertible', '4dr SUV', 'Pickup'],
       'MSRP': [2000, 27150, 54990, 34450, 32340]}

In [159]:
df = pd.DataFrame(data)

In [160]:
df.head(2)

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan  Stanza  1991      138.0                 4            MANUAL   
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   

  Vehicle Style   MSRP  
0         sedan   2000  
1         Sedan  27150

In [161]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [162]:
df['Vehicle Style']

0          sedan
1          Sedan
2    convertible
3        4dr SUV
4         Pickup
Name: Vehicle Style, dtype: object

In [163]:
df[['Make','Model','MSRP']]

Make    Model   MSRP
0   Nissan   Stanza   2000
1  Hyundai   Sonata  27150
2    Lotus    Elise  54990
3      GMC   Acadia  34450
4   Nissan  Frontia  32340

In [164]:
df['Id'] = [1,2,3,4,5]  # Add Column

In [165]:
df

Make    Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan   Stanza  1991      138.0                 4            MANUAL   
1  Hyundai   Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus    Elise  2010      218.0                 4            MANUAL   
3      GMC   Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontia  2017      261.0                 6            MANUAL   

  Vehicle Style   MSRP  Id  
0         sedan   2000   1  
1         Sedan  27150   2  
2   convertible  54990   3  
3       4dr SUV  34450   4  
4        Pickup  32340   5

In [166]:
df

Make    Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan   Stanza  1991      138.0                 4            MANUAL   
1  Hyundai   Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus    Elise  2010      218.0                 4            MANUAL   
3      GMC   Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontia  2017      261.0                 6            MANUAL   

  Vehicle Style   MSRP  Id  
0         sedan   2000   1  
1         Sedan  27150   2  
2   convertible  54990   3  
3       4dr SUV  34450   4  
4        Pickup  32340   5

In [167]:
df1 = df.drop('Id', axis =1)
df1

Make    Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan   Stanza  1991      138.0                 4            MANUAL   
1  Hyundai   Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus    Elise  2010      218.0                 4            MANUAL   
3      GMC   Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontia  2017      261.0                 6            MANUAL   

  Vehicle Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [168]:
df

Make    Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan   Stanza  1991      138.0                 4            MANUAL   
1  Hyundai   Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus    Elise  2010      218.0                 4            MANUAL   
3      GMC   Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontia  2017      261.0                 6            MANUAL   

  Vehicle Style   MSRP  Id  
0         sedan   2000   1  
1         Sedan  27150   2  
2   convertible  54990   3  
3       4dr SUV  34450   4  
4        Pickup  32340   5

In [169]:
del df['Id']

In [170]:
df

Make    Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan   Stanza  1991      138.0                 4            MANUAL   
1  Hyundai   Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus    Elise  2010      218.0                 4            MANUAL   
3      GMC   Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontia  2017      261.0                 6            MANUAL   

  Vehicle Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

#### Index

In [171]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [172]:
df.loc[[1, 2]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle Style   MSRP  
1         Sedan  27150  
2   convertible  54990

In [173]:
df.index = ['a','b','c','d','e']

In [174]:
df

Make    Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan   Stanza  1991      138.0                 4            MANUAL   
b  Hyundai   Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus    Elise  2010      218.0                 4            MANUAL   
d      GMC   Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontia  2017      261.0                 6            MANUAL   

  Vehicle Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [175]:
df.loc['b']

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle Style            Sedan
MSRP                     27150
Name: b, dtype: object

In [176]:
df.iloc[[1,2]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle Style   MSRP  
b         Sedan  27150  
c   convertible  54990

In [222]:
df.at[1, 'Engine Cylinders']

4

In [223]:
df.iat[2,3]

218.0

In [224]:
df

Make    Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan   Stanza  1991      138.0                 4            MANUAL   
1  Hyundai   Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus    Elise  2010      218.0                 4            MANUAL   
3      GMC   Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontia  2017      261.0                 6            MANUAL   

  Vehicle Style   MSRP  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [177]:
df.reset_index(drop = True) # To restore index

Make    Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan   Stanza  1991      138.0                 4            MANUAL   
1  Hyundai   Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus    Elise  2010      218.0                 4            MANUAL   
3      GMC   Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontia  2017      261.0                 6            MANUAL   

  Vehicle Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [181]:
df = df.reset_index(drop = True)
df

Make    Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan   Stanza  1991      138.0                 4            MANUAL   
1  Hyundai   Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus    Elise  2010      218.0                 4            MANUAL   
3      GMC   Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontia  2017      261.0                 6            MANUAL   

  Vehicle Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

### Element-wise Operations

In [182]:
df['Engine HP'] / 100

0    1.38
1     NaN
2    2.18
3    1.94
4    2.61
Name: Engine HP, dtype: float64

In [183]:
df['Year'] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

### Filtering

In [185]:
df[df['Year'] >= 2015]

Make    Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai   Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC   Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontia  2017      261.0                 6            MANUAL   

  Vehicle Style   MSRP  
1         Sedan  27150  
3       4dr SUV  34450  
4        Pickup  32340

In [188]:
df[df['Make'] == 'Hyundai']

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   

  Vehicle Style   MSRP  
1         Sedan  27150

In [189]:
df[(df['Make'] == 'Nissan') & (df['Year'] >= 2015)]

Make    Model  Year  Engine HP  Engine Cylinders Transmission Type  \
4  Nissan  Frontia  2017      261.0                 6            MANUAL   

  Vehicle Style   MSRP  
4        Pickup  32340

### String Operations

In [192]:
df['Vehicle Style'].str.lower()  # To change to lower case

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle Style, dtype: object

In [193]:
'machine learning zoomcamp'.replace(' ','_')

'machine_learning_zoomcamp'

In [195]:
df['Vehicle Style'].str.replace(' ','_')   # To replace element in a string

0          sedan
1          Sedan
2    convertible
3        4dr_SUV
4         Pickup
Name: Vehicle Style, dtype: object

In [196]:
df['Vehicle Style'] = df['Vehicle Style'].str.replace(' ','_') 

In [197]:
df

Make    Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan   Stanza  1991      138.0                 4            MANUAL   
1  Hyundai   Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus    Elise  2010      218.0                 4            MANUAL   
3      GMC   Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontia  2017      261.0                 6            MANUAL   

  Vehicle Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr_SUV  34450  
4        Pickup  32340

In [198]:
df['Vehicle Style'] = df['Vehicle Style'].str.lower()

In [199]:
df

Make    Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan   Stanza  1991      138.0                 4            MANUAL   
1  Hyundai   Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus    Elise  2010      218.0                 4            MANUAL   
3      GMC   Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontia  2017      261.0                 6            MANUAL   

  Vehicle Style   MSRP  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

### Summarizing Operators

In [201]:
df['MSRP'].describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [202]:
df['MSRP'].std()

18985.044903818372

In [203]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               5 non-null      object 
 1   Model              5 non-null      object 
 2   Year               5 non-null      int64  
 3   Engine HP          4 non-null      float64
 4   Engine Cylinders   5 non-null      int64  
 5   Transmission Type  5 non-null      object 
 6   Vehicle Style      5 non-null      object 
 7   MSRP               5 non-null      int64  
dtypes: float64(1), int64(3), object(4)
memory usage: 448.0+ bytes


In [208]:
df.describe().round(3)

Year  Engine HP  Engine Cylinders       MSRP
count     5.000      4.000             5.000      5.000
mean   2010.400    202.750             4.400  30186.000
std      11.261     51.299             0.894  18985.045
min    1991.000    138.000             4.000   2000.000
25%    2010.000    180.000             4.000  27150.000
50%    2017.000    206.000             4.000  32340.000
75%    2017.000    228.750             4.000  34450.000
max    2017.000    261.000             6.000  54990.000

In [205]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle Style        0
MSRP                 0
dtype: int64

In [209]:
df.Make.unique()

array(['Nissan', 'Hyundai', 'Lotus', 'GMC'], dtype=object)

In [210]:
df.Make.nunique()

4

In [211]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle Style        4
MSRP                 5
dtype: int64

### Missing Values

In [215]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle Style        0
MSRP                 0
dtype: int64

### Grouping

In [216]:
df.groupby('Transmission Type').MSRP.min()

Transmission Type
AUTOMATIC    27150
MANUAL        2000
Name: MSRP, dtype: int64

### Getting the Numpy Arrays

In [217]:
df.Make.values

array(['Nissan', 'Hyundai', 'Lotus', 'GMC', 'Nissan'], dtype=object)

In [218]:
df['Engine HP'].values

array([138.,  nan, 218., 194., 261.])